### ISSUE TITLE
Driver instalation steps

### ISSUE THREAD

**Issue by illera88** [intelpt/WindowsIntelPT#11]
Hi,
I'm having troubles with using the driver.

I've changed my windows 10 to `Test Mode` and I've compiled the Driver. I followed your instructions and used `sc create intelpt BinPath=%cd%\WindowsPtDriver\x64\Release\WindowsPtDriver.sys` which creates a windows service.

But when I run the PtControlApp I always get:
`Unable to open the Intel PT device object!\r\n`

So it seems that the device `\\.\WindowsIntelPtDev` cannot be opened. 

What am I missing?

**Comment by ajax4sec** [comment]
I use the INSTDRV.EXE to load the driver in Win 10. Also, I need to get into the advanced reboot to disable the driver signature enforcement.

**Comment by illera88** [comment]
<img width="225" alt="2018-03-07 16_44_19-instdrv" src="https://user-images.githubusercontent.com/5193128/37101854-d375b3bc-2226-11e8-9ce6-c2358bcbbb29.png">

It says invalid service name :(

**Comment by illera88** [comment]
The double quotes were the problem `"`
