### ISSUE TITLE
PMI callback routine not called

### ISSUE THREAD

**Issue by TomSie** [intelpt/WindowsIntelPT#3]
Hey,

the PMI callback routine is not called in case the project is compiled in "Release" mode.

The reason thereof is that the "KeInsertQueueApc" call in the IntelPt.cpp is inside an "ASSERT". Consequently, it is not executed in "Release" mode as in this environment ASSERT is defined as:

#define ASSERT( exp )         ((void) 0)

Best Regards!
Tom

**Comment by richinseattle** [comment]
Thank you for your report, this issue was fixed in https://github.com/intelpt/WindowsIntelPT/commit/95e664337b564afc5d308eff7107660cd8fd6478
