### ISSUE TITLE
Kabylake support?

### ISSUE THREAD

**Issue by howknows** [intelpt/WindowsIntelPT#4]
My CPU is Intel i5 7500 ,does this project support Intel Kabylake architecture? Thanks!

**Comment by richinseattle** [comment]
I do not have Kaby Lake to test, but PT is supported by the architecture and I believe the current release x64 build of our driver should work for you. Please test it with the PtControlApp and let us know. I'll keep this issue open for a little while so you can report back. Thanks!

**Comment by howknows** [comment]
Kaby Lake is support PT ! 👍
