### ISSUE TITLE
System Crash after Windows 10 update

### ISSUE THREAD

**Issue by ajax4sec** [intelpt/WindowsIntelPT#7]
I don't know why the driver may cause the windows 10 system crashed with blue screen. So I keep my system at the version of windows 10 profession version x64 (10.0, version 10240). Have you ever tested the project at the latest version of windows 10? Thank you for your attention,

**Comment by howknows** [comment]
Attach Kernel Debug first ,I want to see the stack backtrace when the system crash.

**Comment by moflow** [comment]
Sorry, the driver has not been tested on new versions of Windows since
August. I will try to give it some attention soon (first weeks of March)

**Comment by DACHOPRA** [comment]
I am seeing the Win10 blue screen issue as well. Which one is the recommended version to work with?

**Comment by richinseattle** [comment]
This is due to a mitigation for a intelpt based patchguard bypass, we are tracking this in another issue:
https://github.com/intelpt/WindowsIntelPT/issues/6
